charts/search/Chart.yaml
- Closes #
**What**
**Why**
**How**
**Tests**
=> ci: bump Chart version to v0.0.3

charts/search/Chart.yaml
- Closes #
**What**
**Why**
**How**
**Tests**
=> ci: bump Chart version to v0.0.3 (#8)

.github/workflows/release.yml
- Closes #
**What**
**Why**
**How**
**Tests**
=> ci: bump tags on release workflow (#10)

.github/workflows/release.yml
- Closes #
**What**
**Why**
**How**
**Tests**
=> fix: remove condition expecting pr merge (#12)

.github/workflows/release.yml
- Closes #
**What**
**Why**
**How**
**Tests**
=> fix: make single job in release workflow, bump patch instead of minor

.github/workflows/release.yml
- Closes #
**What**
**Why**
**How**
**Tests**
=> fix: add write permissions to release workflow

charts/search/Chart.yaml
- Closes #
**What**
**Why**
**How**
**Tests**
=> ci: bump chart version to trigger release

.github/workflows/release.yml
- Closes #
**What**
**Why**
**How**
**Tests**
=> fix: clean release github action

charts/search/templates/search/configmap.yaml
- Closes #
**What**
**Why**
**How**
**Tests**
=> fix: update search environment variables

charts/search/Chart.yaml
- Closes #
**What**
**Why**
**How**
**Tests**
=> ci: bump chart version

README.md
- Closes #
**What**
Change all instances of `Retake` to `ParadeDB`.
**Why**
Because the helm charts now are used for the paradedb project.
**How**
Renaming
**Tests**
N/A
=> docs: update README.md with ParadeDB naming

charts/paradedb/Chart.yaml, charts/paradedb/values.yaml
N/A
**What**
Rename the condition to install the operator for pgo.
**Why**
There was a leftover reference to opensearch.
**How**
Rename
**Tests**
N/A
=> fix: operator conditional for pgo

charts/paradedb/Chart.yaml, charts/paradedb/templates/cluster.yaml, charts/paradedb/values.yaml
N/A
**What**
Adds support for specifying the monitoring section on the chart. This will make it possible to start the monitoring stack on each deployment.
**Why**
Because monitoring is a desirable feature to have, and we need to add support for it.
**How**
Add the monitoring section to the template.
**Tests**
Tested manually and the metrics are exported successfully and can be visualized with Grafana.
=> feat: add monitoring section

charts/paradedb/Chart.yaml
- Closes #
**What**
**Why**
**How**
**Tests**
=> chore: manually bump version to 0.2.30

charts/paradedb/Chart.yaml, charts/paradedb/values.yaml
- Closes #
**What**
**Why**
**How**
**Tests**
=> fix: remove pgml from preload list

charts/paradedb/Chart.yaml, charts/paradedb/values.yaml
- Closes #
**What**
Add the vacuum command to the initsql commands.
**Why**
It was accidentally removed in #52 
**How**
**Tests**
=> fix: add vaccum command again

charts/paradedb/Chart.yaml
- Closes #
**What**
**Why**
**How**
**Tests**
=> chore: manually bump version

.github/workflows/publish-helm-chart.yml
=> fix: Proper url for tag retrieval

.github/workflows/publish-helm-chart.yml
=> fix: Proper variable for release workflow

.github/workflows/publish-helm-chart.yml
=> fix: Fix quotes in version upgrade

.github/workflows/publish-helm-chart.yml
=> fix: Reorder workflow to properly increment

.github/workflows/lint-helm.yml
- Closes #
It wasn't being triggered
=> fix: Fix lint condition

README.md
=> chore: Add badge

artifacthub-repo.yml
=> chore: Rm artifacthub-repo.yml, it needs to be in the gh-pages branch

.github/config/chart-releaser.yml, .github/workflows/publish-helm-chart.yml
- Closes #
This will allow us to get verified on ArtifactHub
=> feat: Sign Helm charts for ArtifactHub

.github/workflows/publish-helm-chart.yml
=> fix: Fix GitHub Secrets

.github/config/cr.yaml, .github/workflows/publish-helm-chart.yml, charts/paradedb/Chart.yaml
=> feat: Sign Helm Chart for ArtifactHub

charts/paradedb/values.yaml
=> feat: Remove extra extensions, and upgrade to PG16

charts/paradedb/values.yaml
- Closes #
This was not needed now that we do use `pgsodium`
=> chore: Remove `pgcrypto`

.github/CODEOWNERS, charts/paradedb/values.yaml
- Closes #N/A
Adapt to the Bitnami container
We swapped our Dockerfile
Add extra preload_libraries
N/A
=> feat: Adapt values.yml to the Bitnami container

.github/workflows/lint-helm.yml, README.md, charts/paradedb/Chart.yaml, charts/paradedb/values.yaml
=> chore: Cleanup

.github/workflows/lint-format.yml, .github/workflows/lint-helm.yml, .github/workflows/lint-markdown.yml, .github/workflows/lint-pr-title.yml, .github/workflows/lint-yaml.yml, .github/workflows/publish-helm-chart.yml
- Closes #
We've made this change in the monorepo, and I figured we should do it here too.
=> chore: Only run on non-draft

CONTRIBUTING.md
=> chore: Typo

CONTRIBUTING.md, README.md
=> chore: Update Slack invite link

README.md
=> chore: Add Docker pulls to README
